/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Nightly Tester Tools.
 *
 * The Initial Developer of the Original Code is
 *      Dave Townsend <dave.townsend@blueprintit.co.uk>.
 *
 * Portions created by the Initial Developer are Copyright (C) 2006
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK *****
 *
 * $HeadURL: svn://svn.blueprintit.co.uk/dave/mozilla/firefox/buildid/trunk/components/nsNightlyToolsService.js $
 * $LastChangedBy: dave $
 * $Date: 2005-09-10 19:52:42 +0100 (Sat, 10 Sep 2005) $
 * $Revision: 152 $
 *
 */

#include "nsISupports.idl"

interface nsIArray;
interface nsITreeView;
interface nsITalkbackIncident;
interface nsITalkbackBuild;
interface nsITalkbackPlatform;
interface nsITalkbackProduct;
interface nsITalkbackVendor;
interface nsITalkbackService;

[scriptable, uuid(c5d596d3-596f-4681-8c27-2df00ac62b9e)]
interface nsITalkbackIncident : nsISupports
{
	readonly attribute nsITalkbackBuild build;

	readonly attribute long date;
	readonly attribute AString id;
	readonly attribute AString comment;
};

[scriptable, uuid(56f89015-6d25-4c0f-b584-87fcc255fbf2)]
interface nsITalkbackBuild : nsISupports
{
	readonly attribute AString name;
	readonly attribute nsITalkbackPlatform platform;

	nsITalkbackIncident getIncident(in AString id);
	nsIArray getIncidents();
	
	void remove();
};

[scriptable, uuid(0e826469-593d-4b1f-a01e-416ddbe7ec94)]
interface nsITalkbackPlatform : nsISupports
{
	readonly attribute AString name;
	readonly attribute nsITalkbackProduct product;

	nsITalkbackBuild getBuild(in AString name);
	nsIArray getBuilds();
	
	void remove();
};

[scriptable, uuid(21ee50dc-0137-400f-b143-788caec31872)]
interface nsITalkbackProduct : nsISupports
{
	readonly attribute AString name;
	readonly attribute nsITalkbackVendor vendor;

	nsITalkbackPlatform getPlatform(in AString name);
	nsIArray getPlatforms();
	
	void remove();
};

[scriptable, uuid(0b4d1cdb-2666-4d42-a322-da928004e625)]
interface nsITalkbackVendor : nsISupports
{
	readonly attribute AString name;

	nsITalkbackProduct getProduct(in AString name);
	nsIArray getProducts();
	
	void remove();
};

[scriptable, uuid(943acc93-a529-4fb9-98d5-7e4a733953d2)]
interface nsITalkbackService : nsISupports
{
	readonly attribute nsITalkbackBuild currentBuild;

	nsIArray getRecentIncidents(in long date);
	nsIArray getPreviousIncidents(in long count);

	nsITalkbackIncident getIncident(in AString id);
	nsITalkbackVendor getVendor(in AString name);
	nsIArray getIncidents();
	nsIArray getVendors();
	
	nsITreeView getTreeView();
};
